// Inline the fetched assets (assets-src/*) into js/assets.js as base64 data URIs.
// Run after scripts/fetch-assets.sh. This is what lets index.html work from file://
// with zero network fetches.
//
//   node scripts/build-assets.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'assets-src');

const dataUri = (file, mime) =>
  `data:${mime};base64,${readFileSync(join(src, file)).toString('base64')}`;

const assets = {
  gradient: dataUri('gradient.png', 'image/png'),
  illustration: dataUri('illustration.svg', 'image/svg+xml'),
  // project-logo variants (component set "project-logo" in Figma)
  logoHa: dataUri('logo-ha.svg', 'image/svg+xml'),
  logoEsphome: dataUri('logo-esphome.svg', 'image/svg+xml'),
  logoMa: dataUri('logo-ma.svg', 'image/svg+xml'),
  figtree400: dataUri('figtree-400.woff2', 'font/woff2'),
  figtree700: dataUri('figtree-700.woff2', 'font/woff2'),
};

const out =
  '// AUTO-GENERATED by scripts/build-assets.mjs — do not edit by hand.\n' +
  '// Base64 data URIs for all fixed visual assets + the Figtree webfont,\n' +
  '// so the app runs from file:// with no network requests.\n' +
  'window.ASSETS = ' + JSON.stringify(assets, null, 0) + ';\n';

writeFileSync(join(root, 'js', 'assets.js'), out);
const kb = (Buffer.byteLength(out) / 1024).toFixed(0);
console.log(`Wrote js/assets.js (${kb} KB)`);
